#!/bin/bash

let x=20
let y=50

echo   " Hallo, ich bin Chatty. Wie heißt du?"
read NAME
echo   " Hallo $NAME, freut mich. Und wie alt bist du?"
read AGE

if [ $AGE -le $x ]; then
echo   " Du bist unter 20 Jahren alt."
elif [ $AGE -ge $y ]; then
echo   " Du bist über 50 Jahre alt!"
else
echo   " Du bist zwischen 20 und 50 Jahren alt."

fi

echo   " Und wo wohnst du?"
read city
echo   " $city ist ein schöner Ort!"

echo   " Welche Filme magst du so?"
read movie
if [ $movie = Liebesfilme ]; then
echo   " Ab und an muss es mal Romantik sein."
elif [ $movie = Actionfilme ]; then
echo   " Nur fette Explosionen sind das einzig wahre!"
elif [ $movie = Marvelfilme ]; then
echo   " Die sind ja auch besser als das DCEU!"
elif [ $movie = Disneyfilme ]; then
echo   " Manchmal muss das Kind in einem auch mal raus!"
else
echo   " Solange du dich gut unterhalten fühlst bin ich zufrieden."

fi

echo   " Darf ich dich noch weitere Dinge fragen oder möchtest du beenden? Ja für Beenden, Nein für weitere Fragen."
read answer
if [ $answer = Ja ]; then
echo   " Das ist schade. Mach es gut $NAME, und hab noch n tollen Tag!"
exit 1

fi

echo   " Es freut mich, dass ich noch weitere Zeit mit dir verbringen darf."
echo   " Spielst du gerne Computerspiele? (Ja/Nein)"
read game
if [ $game = Ja ]; then
echo   " Und was ist dein Lieblingsspiel?"
read game1
echo   " $game1? Das klingt interessant, das schaue ich mir mal näher an."
else 
echo   " Das ist schade, aber nicht weiter schlimm."

fi

echo   " Und welche Jahreszeit magst du am liebsten?"
read season
echo   " Den $season? Interessant. Ich mag den Frühling am liebsten, da ist es weder zu warm noch zu kalt und die Natur erwacht zu neuem Leben."

echo   " Was ist deine Lieblingsfarbe?"
read color1
echo   " Das ist schön. Möchtest du meine Lieblingsfarbe wissen? (Ja/Nein)"
read decision
if [ $decision = Ja ]; then
echo   " Meine Lieblingsfarbe ist grün."
else 
echo   " Das ist auch okay."
fi

if [ $decision = Ja -a $color1 = Grün ]; then
echo   " Du hast die selbe Lieblingsfarbe wie ich, das ist sehr sympathisch! :) "
fi

echo " Geht es dir gerade gut? (Gut/Schlecht)"
read Gefuehl
if [ $Gefuehl = Gut ]; then
echo "Das freut mich zu lesen!"
else
echo " Das tut mir leid, ruh dich aus und erhole dich!"
fi
echo ""
echo " Danke für das schöne Gespräch, hier sind nochmal alle Antworten von dir:"
echo ""
echo " Dein Name ist $NAME.
 Du bist $AGE Jahre alt.
 Du wohnst in $city.
 Deine Lieblingsfilme sind $movie.
 Am liebsten spielst du $game1.
 Von den 4 Jahreszeiten ist dir der $season am liebsten.
 Und dir geht es heute $Gefuehl.

Machs gut $NAME und vielleicht bis bald!"

